# TravisCI configuration file, see
# https://docs.travis-ci.com/user/languages/r/
language: r
cache: packages
sudo: false
env:
  matrix:
    - ORCID_ID="0000-0002-3520-2046"
script: Rscript checkmydois.R
